#docker-compose up --build
#docker-compose down --rmi all
version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - C:\Proyectos\docker\wordpress\wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - C:\Proyectos\docker\wordpress\db_data:/var/lib/mysql
